[@ui.bambooSection titleKey="section.connection"]
    [@ww.select labelKey="label.region" name="region" required='true' list="regionList"/]
    [@ui.bambooSection dependsOn="region" showOn="OTHER"]
        [@ww.textfield labelKey="label.otherRegion" name="otherRegion"/]
    [/@ui.bambooSection]
    [@ww.select labelKey="label.credentialList" name="selectedCred" required="true" list="credentialList"/]
    [@ww.textfield  labelKey="label.appName" name="appName" required='true'/]
    [@ww.textfield labelKey="label.scanConfigName" name="scanConfigName" required='true'/]
[/@ui.bambooSection]

[@ui.bambooSection titleKey="section.action"]
    [@ww.select labelKey="label.advanceOn" name="advanceOn" required="true" list="advanceOnOptions"/]
[/@ui.bambooSection]

[@ui.bambooSection titleKey="section.status" dependsOn="advanceOn" showOn="STARTED"]
    [@ww.textfield labelKey="label.statusCheckInterval" name="checkInterval"/]
    [@ww.textfield labelKey="label.maxPendingDuration" name="maxPending"/]
[/@ui.bambooSection]

[@ui.bambooSection titleKey="section.status" dependsOn="advanceOn" showOn="COMPLETED"]
    [@ww.textfield labelKey="label.statusCheckInterval" name="checkInterval"/]
    [@ww.textfield labelKey="label.maxPendingDuration" name="maxPending"/]
    [@ww.textfield labelKey="label.maxExecutionDuration" name="maxExecution"/]
    [@ww.checkbox  labelKey="label.findingsReportGeneration" name="findingsReportGeneration" toggle='true'/]
    [@ww.checkbox  labelKey="label.vulnQueryEnforcement" name="vulnQueryEnforcement" toggle='true'/]
[/@ui.bambooSection]

[@ui.bambooSection titleKey="section.gating" descriptionKey="section.gating.details" dependsOn="vulnQueryEnforcement" showOn="true"]
    [@ww.textfield labelKey="label.vulnQuery" name="vulnQuery"/]
[/@ui.bambooSection]