name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Atlassian SDK
      run: |
        sudo sh -c 'echo "deb https://packages.atlassian.com/debian/atlassian-sdk-deb/ stable contrib" >>/etc/apt/sources.list'
        wget https://packages.atlassian.com/api/gpg/key/public  
        sudo apt-key add public
        sudo apt-get update
        sudo apt-get install atlassian-plugin-sdk
    - name: Validate SDK
      run: |
        atlas-version
    - name: Test Project
      run: |
        atlas-clean
        atlas-unit-test
